libc: newlib: fixes to ensure that the lua module sample works
Previously, the lua sample was not linking correctly against newlib for
xtensa.

Several internal libc symbols were missing, exclusively for xtensa, so
they were added.

```shell
west build -p -b qemu_xtensa ../modules/lua/samples/app \
-- -DCONFIG_POSIX_API=y
```

Linking failed with the following error.

```
ZEPHYR_SDK_INSTALL_DIR/xtensa-dc233c_zephyr-elf/xtensa-dc233c_zephyr-elf\
/lib/./libc.a(lib_a-fdopen.o): in function `fdopen':
fdopen.c:(.text.fdopen+0x0): multiple definition of `fdopen'; \
  zephyr/lib/posix/options/liblib__posix__options.a(device_io.c.obj): \
  HOME/zephyrproject/zephyr/lib/posix/options/device_io.c:53: \
first defined here
```

So Zephyr's fdopen is not linked for newlib. The newlib version may not work
as intended for all purposes.

Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>